### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jeton-th**

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi @jeton-th ,

First of all don't put `package.json`, `eslint.js` in **gitignore**. Also please delete **node_module** folder from your local repo. Then push it first without run `nmp install`. What will happen after that? it will also remove node folder from your origin means from the GitHub server. Before applying this process also remove `pakaje.json`, `eslint.js` from **gitignore**. Then push those file in the remote server. After doing all those tasks send another request to re-review this project. If you need any clarification for this feedback then knock me on slack or leave a comment here (**_Don't use GitHub quote reply option for this_**).



Another thing, please fix all the **eslint** issues (_that stickler linter_). You can use **eslint** auto fixing features. How to do it? Here is the [doc](https://eslint.org/docs/user-guide/command-line-interface#--fix).

#### P.S [A good [resource](https://www.youtube.com/watch?v=MpGLUVbqoYQ) about how to use webpack. You can take a look on that ] 

Thanks 🙏

**Comment by jeton-th** [comment]
Hi @dipto0321 

Thanks for the feedback. I removed the **node_modules** folder and I also removed the **.gitignore** file (since it remained empty after removing the lines you asked me).

As for the linting errors, they are coming from `main.js` file which is auto generated from **webpack**.
There are no linting errors from my code. 

Do you have any additional suggestion?

**Comment by dipto0321** [comment]
Hi @jeton-th ,

Good job that you bring back `package.json` and `eslint.js` files. But why you delete `.gitignore` ? `node_module` should be there. Please check that ☝️ picture properly. I mentioned deleting only **line 2 and 3** from **gitignore**. That's is. Another thing is that in the package.json I did not find any webpack as devDependencies. So can you please properly complete the `package.json` with adding proper packages for this project. Here is the minimum checklist to make this project complete.

### Project Specification Shortcut

#### Application
- [ ] All necessarily used packages should be included in `package.json`
- [ ] Necessary run common commands like `build`, `development` should be in `package.json` inside `script'
- [ ] It uses Webpack
- [ ] It includes a rule for the `node_modules` directory on `.gitignore`
- [x] It appends HTML elements to the `<div>` with `id=content` when the page is loaded (Use `document.createElement` and `document.appendChild`
- [x] It features a tabbed menu. When a tab is clicked the content is replaced
- [x] The contents of each tab are stored in a `module`.
- [x] Each `module` exports a function that creates a `<div>` element, adds the appropriate content and styles to that element and then appends it to the DOM.

##### Source directory (src)
- [x] It has an entry point named index.js

##### Distribution directory (dist)
- [x] It has a main file named index.html
- [x] It has a main.js file that is built by webpack
- [x] The index.html links the main.js file

Please send another request after fixing `package.json` and `.gitignore` to make this project complete.

Thanks 🙂

**Comment by dipto0321** [comment]
Hi @jeton-th ,

Awesome! You are good to go. This is from me 👍 .

Thanks for co-operating with me ☺️

**Pull request merged**
